### ISSUE TITLE
Application Crash on SB Connection

### ISSUE THREAD

**Issue by csuriano23** [telstrapurple/PurpleExplorer#43]
I am connecting with the string:

`Endpoint=sb://<my_service_bus>.servicebus.windows.net/;SharedAccessKeyName=<name>;SharedAccessKey=<key>`

(not specific to a topic, as in previously closed issues), but I receive this stacktrace:

```
Unhandled exception. Microsoft.Azure.ServiceBus.UnauthorizedException: User is not authorized. TrackingId:672b3d2b-7f71-418d-aa35-75f20749d7b5_G26, SystemTracker:XXX.servicebus.windows.net:$namespaceinfo, Timestamp:2021-12-10T13:47:34
   at Microsoft.Azure.ServiceBus.Management.ManagementClient.SendHttpRequest(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.ServiceBus.Management.ManagementClient.GetEntity(String path, String query, Boolean enrich, CancellationToken cancellationToken)
   at Microsoft.Azure.ServiceBus.Management.ManagementClient.GetNamespaceInfoAsync(CancellationToken cancellationToken)
   at PurpleExplorer.Helpers.TopicHelper.GetNamespaceInfo(String connectionString) in /Users/runner/work/PurpleExplorer/PurpleExplorer/PurpleExplorer/Helpers/TopicHelper.cs:line 97
   at PurpleExplorer.ViewModels.MainWindowViewModel.ConnectionBtnPopupCommand() in /Users/runner/work/PurpleExplorer/PurpleExplorer/PurpleExplorer/ViewModels/MainWindowViewModel.cs:line 183
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 39
   at Avalonia.Native.Interop.Impl.__MicroComIAvnSignaledCallbackVTable.Signaled(IntPtr this, Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/Interop.Generated.cs:line 3602
--- End of stack trace from previous location where exception was thrown ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 92
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 62
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 108
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at PurpleExplorer.Program.Main(String[] args) in /Users/runner/work/PurpleExplorer/PurpleExplorer/PurpleExplorer/Program.cs:line 11
[1]    34621 abort      ./PurpleExplorer
```

I also managed to connect to azure with `az login` in the same CLI session before launching PurpleExplorer

**Comment by csuriano23** [comment]
Sorry, I solved switching to credentials under RootManageSharedAccessKey policy. Closing ...
