### ISSUE TITLE
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Avalonia.Themes.Default

### ISSUE THREAD

**Issue by nemetht** [telstrapurple/PurpleExplorer#58]
inxi                                                 

CPU: quad core Intel Core i7-8650U (-MT MCP-) speed/min/max: 800/400/4200 MHz
Kernel: 5.18.5-1-MANJARO x86_64 Up: 1h 17m Mem: 12893.7/15860.3 MiB (81.3%)
Storage: 476.94 GiB (63.8% used) Procs: 348 Shell: Zsh inxi: 3.3.19

-------------------------------------
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Avalonia.Themes.Default, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'Avalonia.Themes.Default, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(String name) in /_/src/Shared/PlatformSupport/AssetLoader.cs:line 242
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetResAsmAndPath(Uri uri) in /_/src/Shared/PlatformSupport/AssetLoader.cs:line 193
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(Uri uri) in /_/src/Shared/PlatformSupport/AssetLoader.cs:line 204
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(Uri uri, Uri baseUri) in /_/src/Shared/PlatformSupport/AssetLoader.cs:line 103
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri) in /_/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs:line 50
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded() in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 54
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 98
   at Avalonia.Styling.Styles.<OnCollectionChanged>g__Add|52_1(IList items) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 287
   at Avalonia.Styling.Styles.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 318
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 687
   at Avalonia.Collections.AvaloniaList`1.Add(T item) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 205
   at Avalonia.Styling.Styles.Add(IStyle item) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 201
   at PurpleExplorer.App.!XamlIlPopulate(IServiceProvider , App ) in /Users/runner/work/PurpleExplorer/PurpleExplorer/PurpleExplorer/App.xaml:line 12
   at PurpleExplorer.App.!XamlIlPopulateTrampoline(App )
   at PurpleExplorer.App.Initialize() in /Users/runner/work/PurpleExplorer/PurpleExplorer/PurpleExplorer/App.xaml.cs:line 19
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 310
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at PurpleExplorer.Program.Main(String[] args) in /Users/runner/work/PurpleExplorer/PurpleExplorer/PurpleExplorer/Program.cs:line 13

**Comment by armannaj** [comment]
What version are you using? Is it the same with the latest released version?

**Comment by armannaj** [comment]
Confirmed and fixed it in v0.1.14
