### ISSUE TITLE
Getting Below error while selecting queue on app

### ISSUE THREAD

**Issue by ManasGi** [telstrapurple/PurpleExplorer#61]
Unhandled exception. System.ArgumentNullException: Array cannot be null. (Parameter 'bytes')
   at System.Text.Encoding.GetString(Byte[] bytes)
   at System.Text.UTF8Encoding.UTF8EncodingSealed.GetString(Byte[] bytes)
   at PurpleExplorer.Models.Message..ctor(Message azureMessage, Boolean isDlq)
   at PurpleExplorer.Helpers.QueueHelper.<>c.<GetDlqMessages>b__6_0(Message message)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at PurpleExplorer.Helpers.QueueHelper.GetDlqMessages(String connectionString, String queueName)
   at PurpleExplorer.ViewModels.MainWindowViewModel.FetchQueueDlqMessages()
   at PurpleExplorer.ViewModels.MainWindowViewModel.FetchMessages()
   at PurpleExplorer.Views.MainWindow.TreeView_SelectionChanged(Object sender, SelectionChangedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 39
   at Avalonia.Native.Interop.Impl.__MicroComIAvnSignaledCallbackVTable.Signaled(Void* this, Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/Interop.Generated.cs:line 4336
--- End of stack trace from previous location ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 90
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at PurpleExplorer.Program.Main(String[] args)
zsh: abort      /Users/manas.gupta/Downloads/PurpleExplorer_osx-x64\ \(1\)/PurpleExplorer

Saving session...
...copying shared history...
...saving history...truncating history files...

**Comment by armannaj** [comment]
Thanks for reporting this @ManasGi  I'm having a look

**Comment by armannaj** [comment]
seems like the issue happens when message body is not set.

fixed it in PR #62 . It will be in the next release.

**Comment by ManasGi** [comment]
Thanks @armannaj for addressing the issue.
